### ISSUE TITLE
Readme Please

### ISSUE THREAD

**Issue by gavingc** [oberien/hp-x360-elan-fix#1]
Hi,
I have the 15 inch HP Spectre with the same challenges running Debian Buster.
Could we please get a small README.md outlining how you have been compiling and using your button fix?

**Comment by oberien** [comment]
Which version of libinput are you running (`libinput --version`)?

**Comment by gavingc** [comment]
1.12.6

**Comment by oberien** [comment]
I added a proper build process and documented it in the README. Feel free to open another issue / respond to this one if you have any questions, problems or suggestions.

**Comment by gavingc** [comment]
Much appreciated.
